### ISSUE TITLE
Files on the AramisLab server need updates

### ISSUE THREAD

**Issue by thibaultdvx** [aramis-lab/clinicadl_handbook#26]
Some files on the AramisLab server have already been updated by @NicolasGensollen to have (see #23):
- 3 digits session labels
- pet tracers respecting the BIDS naming convention

Nevertheless, several files useful to run the handbook still need to be updated (the list will possibly grow as I have not checked all the files yet):

In https://aramislab.paris.inria.fr/clinicadl/files/handbook_2023/data_oasis/:

- [x] iotools_output.tar.gz

In https://aramislab.paris.inria.fr/clinicadl/files/handbook_2023/data_adni/:

- [x]  CAPS_example.tar.gz
- [x]  iotools_output.tar.gz

On the git repo of the handbook:

- [x]  data/adni_after_qc.tsv (PR #29)
- [x]  data/oasis_after_qc.tsv (PR #29)
- [x]  data/analysis_oasis.tsv (PR #29)
- [x]  data/analysis_adni.tsv (PR #29)

**Comment by NicolasGensollen** [comment]
Thanks for tracking down these issues @thibaultdvx !
I'll take care of these updates some time this week.

**Comment by thibaultdvx** [comment]
completed in #30
